apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nepai-ingress
  namespace: nepai
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: nepai.pulami.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nepai-service
            port:
              number: 80
