apiVersion: v1
kind: Secret
metadata:
  name: nepai-secrets
  namespace: nepai
type: Opaque
stringData:
  # Clerk
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "your_clerk_publishable_key"
  CLERK_SECRET_KEY: "your_clerk_secret_key"
  
  # MongoDB
  MONGODB_URI: "your_mongodb_connection_string"
  
  # Redis
  UPSTASH_REDIS_URL: "your_upstash_redis_url"
  
  # OpenAI
  OPENAI_API_KEY: "your_openai_api_key"